version: '3.9'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app # Dockerfile의 WORKDIR와 맞추기
      - /usr/src/app/node_modules # 핫 리로드 성능 개선
      
    environment: 
      - CHOKIDAR_USEPOLLING=true 

    stdin_open: true

# docker compose up -d
# docker compose down
# docker compose up --build
# docker compose -f docker-compose.dev.yml up --build